### ISSUE TITLE
遇到了一点问题

### ISSUE THREAD

**Issue by Jonathon52306** [ma6254/FictionDown#11]
在搜索盗版的时候会出现“404 404 Not Found”的问题，换了好多网站都是这样
盗版搜索前是要现在“.FictionDown"文件中输入盗版网站就可以了吗

**Comment by Jonathon52306** [comment]
是我的打开方式不对吗

**Comment by ma6254** [comment]
盗版搜索是`search`子命令，usage如下

```
NAME:
    search - 检索盗版站点

USAGE:
    search [command options] [arguments...]

OPTIONS:
   -k value, --keyword value  搜索关键词
   --put, -p                  对比并放入缓存文件
```

之前某版本中的一个网站搜索API失效报404错误
网站为`https://www.biqiuge.com/`
对应搜索API地址为`https://so.biqusoso.com/s.php`
已在最新的commit`3578671`中禁用该网站的搜索并优化搜索逻辑
编译该commit即可

**Comment by Jonathon52306** [comment]
所以是要将网站预先输入到“.FictionDown"文件中吗

**Comment by Jonathon52306** [comment]
还有如何进行编译？需要安装哪些软件？

**Comment by Jonathon52306** [comment]
2020/02/15 18:01:29 URL: "https://book.qidian.com/info/1016313375"
2020/02/15 18:01:29 use golang default http
2020/02/15 18:01:30 Loading....
2020/02/15 18:01:30 yaml: unmarshal errors:
  line 1: cannot unmarshal !!str `https:/...` into store.Store
这个问题如何解决

**Comment by ma6254** [comment]
> 2020/02/15 18:01:29 URL: "[book.qidian.com/info/1016313375](https://book.qidian.com/info/1016313375)"
> 2020/02/15 18:01:29 use golang default http
> 2020/02/15 18:01:30 Loading....
> 2020/02/15 18:01:30 yaml: unmarshal errors:
> line 1: cannot unmarshal !!str `https:/...` into store.Store
> 这个问题如何解决

这个报错是yaml文件解析错误，是修改缓存文件失误导致的

**Comment by ma6254** [comment]
> 还有如何进行编译？需要安装哪些软件？

需要安装Golang开发环境，要求版本大于1.11
简要操作在README中

**Comment by Jonathon52306** [comment]
谢谢！
问题解决了，但是下载某些章节的时候会有这样的错误：
020/02/15 18:44:29 Error: 第一百九十章 难以触碰的禁区手术（第一更） https://www.biquge5200.cc/127_127950/170712080.html "https://www.biquge5200.cc/127_127950/170712080.html" 503 Service Unavailable
 178 / 196 [==================================================================================================>---------]  90.82% 00m02s2020/02/15 18:44:29 Error: 第一百八十四章 高位复杂性肛瘘（第一更） https://www.biquge5200.cc/127_127950/170683401.html "https://www.biquge5200.cc/127_127950/170683401.html" 503 Service Unavailable
2020/02/15 18:44:29 错误次数过多，忽略此章节，并尝试更换爬取方式
2020/02/15 18:44:29 Error: 第一百七十五章 熊猫血（第一更） https://www.biquge5200.cc/127_127950/170637427.html Post http://localhost:20202/webpage/Create: dial tcp [::1]:20202: connectex: No connection could be made because the target machine actively refused it.
2020/02/15 18:44:29 错误次数过多，忽略此章节，并尝试更换爬取方式
2020/02/15 18:44:29 Job Error: 爬取方式错误: 2
 178 / 196 [==================================================================================================>---------]  90.82% 00m01s2020/02/15 18:44:31 Error: 第一百九十三章 在刀尖上跳舞（第一更） https://www.biquge5200.cc/127_127950/170728677.html "https://www.biquge5200.cc/127_127950/170728677.html" 503 Service Unavailable
 180 / 196 [===================================================================================================>--------]  91.84% 00m02s2020/02/15 18:44:31 Error: 第一百八十三章 近水楼台先得月（第三更） https://www.biquge5200.cc/127_127950/170668417.html Post http://localhost:20202/webpage/Create: dial tcp [::1]:20202: connectex: No connection could be made because the target machine actively refused it.
2020/02/15 18:44:31 错误次数过多，忽略此章节，并尝试更换爬取方式
2020/02/15 18:44:31 Job Error: 爬取方式错误: 2
 180 / 196 [===================================================================================================>--------]  91.84% 00m01s2020/02/15 18:44:32 Error: 第一百八十四章 高位复杂性肛瘘（第一更） https://www.biquge5200.cc/127_127950/170683401.html Post http://localhost:20202/webpage/Create: dial tcp [::1]:20202: connectex: No connection could be made because the target machine actively refused it.
2020/02/15 18:44:32 错误次数过多，忽略此章节，并尝试更换爬取方式
2020/02/15 18:44:32 Job Error: 爬取方式错误: 2
 181 / 196 [======================================================================================================>--------]  92.35% 32s

**Comment by ma6254** [comment]
这是由于`biquge5200.cc`这个站点反爬策略所致
要减少503错误可通过如下两个方法
## 1. 在缓存文件中禁用该站点

打开缓存文件（.FictionDown文件，格式为yaml文本）
其中的`tmap`项目为盗版站点的地址，将`biquge5200.cc`站点地址删去即可
例如：
```yaml
bookurl: https://book.qidian.com/info/3594144#Catalog
bookname: 超时空垃圾站
author: 小城古道
coverurl: https://bookcover.yuewen.com/qdbimg/349573/3594144/180
description: |-
  苏璟大学毕业后，处处碰壁，心灰意冷，回老家调整心情。却发现自家后院，成了超时空垃圾站，每天都有大量垃圾汇入其中，有的来自神墓、斗破苍穹、盘龙等小说时空；有的来自海贼王、火影、死神等动漫时空；有的来自X战警、美国队长、钢铁侠等漫威时空……作为垃圾站主人，苏璟有处理这些垃圾的义务。一开始他认为这是一件苦差，后来才发现，这是这辈子所遇到过的最美的美差。
  新书《我只想当一个安静的氪金玩家》。
tmap:
- https://www.81new.com/19/19738/
- https://www.biquge5200.cc/3_3380/
volumes:
- name: 作品相关
```
修改后
```yaml
bookurl: https://book.qidian.com/info/3594144#Catalog
bookname: 超时空垃圾站
author: 小城古道
coverurl: https://bookcover.yuewen.com/qdbimg/349573/3594144/180
description: |-
  苏璟大学毕业后，处处碰壁，心灰意冷，回老家调整心情。却发现自家后院，成了超时空垃圾站，每天都有大量垃圾汇入其中，有的来自神墓、斗破苍穹、盘龙等小说时空；有的来自海贼王、火影、死神等动漫时空；有的来自X战警、美国队长、钢铁侠等漫威时空……作为垃圾站主人，苏璟有处理这些垃圾的义务。一开始他认为这是一件苦差，后来才发现，这是这辈子所遇到过的最美的美差。
  新书《我只想当一个安静的氪金玩家》。
tmap:
- https://www.81new.com/19/19738/
volumes:
- name: 作品相关
```
## 2.修改爬取频率

`download`子命令usage为
```bash

╰─$ ./FictionDown_v0.1.2-5-gb7c561b_linux_amd64 download -h
NAME:
    download - 下载缓存文件

USAGE:
    download [command options] [arguments...]

OPTIONS:
   -t value              线程数 (default: 10)
   -f value              输出格式
   -o value              输出路径
   --chromedp-log value  Chromedp log file
   --tsleep value        章节爬取间隔 (default: 200ms)
   --errsleep value      章节爬取错误间隔 (default: 500ms)

```

其中tsleep和errsleep分别为常规爬取间隔和遇到错误时的爬取间隔
调大这两个参数即可，例如1s和2s
